pipeline {
    agent any

    environment {
        IMAGE_NAME = "2022bcs0063sujeet/ml-model:latest"
        CONTAINER_NAME = "wine-api-test"
        PORT = "8000"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Pull Image') {
            steps {
                sh 'docker pull $IMAGE_NAME'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker rm -f $CONTAINER_NAME || true
                docker run -d -p $PORT:8000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }

        stage('Wait for API Readiness') {
            steps {
        sh '''
        echo "Waiting for API..."
        for i in $(seq 1 20); do
          if curl -s http://localhost:$PORT/ > /dev/null; then
            echo "API is ready"
            exit 0
          fi
          echo "Retry $i..."
          sleep 3
        done
        echo "API failed to start"
        exit 1
        '''
    }
}

        stage('Valid Inference Test') {
            steps {
                sh '''
                RESPONSE=$(curl -s -X POST http://localhost:$PORT/predict \
                  -H "Content-Type: application/json" \
                  -d @Lab/tests/valid_input.json)

                echo "Valid Response: $RESPONSE"

                echo $RESPONSE | grep -q "wine_quality" || exit 1
                '''
            }
        }

        stage('Invalid Input Test') {
            steps {
                sh '''
                STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
                  -X POST http://localhost:$PORT/predict \
                  -H "Content-Type: application/json" \
                  -d @Lab/tests/invalid_input.json)

                echo "Invalid status: $STATUS"

                if [ "$STATUS" -eq 200 ]; then
                  echo "Invalid input should fail"
                  exit 1
                fi
                '''
            }
        }

        stage('Stop Container') {
            steps {
                sh 'docker rm -f $CONTAINER_NAME || true'
            }
        }
    }

    post {
        always {
            sh 'docker rm -f $CONTAINER_NAME || true'
        }
    }
}